### ISSUE TITLE
Can't connect to Argo Ulisse DCI 13 Eco Wifi

### ISSUE THREAD

**Issue by shan-vosseller** [nyffchanium/argoclima-integration#9]
## Version of the custom_component

1.1.2 (latest)

## Configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
fan:
  - platform: xiaomi_miio_fan
    name: Living Room Fan
    host: -----
    token: --------
logger:
  default: critical
  logs:
    custom_components.argoclima: debug
```

## Describe the bug

attempting to connect to the AC's IP address fails with error "Could not reach host or host is not a supported device."

## Debug log

all I see is the usual warning about custom component that I see for several of mine
perhaps there's something I'm missing in getting logging to work but I see nothing other than that for argoclima
